=== V1TA5/eli/meta.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://event.log.institute/event-meta.schema.json",
	"title": "Event Meta",
	"description": "Describes the schema of event design meta data",
	"type": "object",
	"properties": {
		"name": {
			"description": "Name of the event",
			"type": "string",
			"exclusiveMinimum": 0
		},
		"license": {
			"description": "License information",
			"type": "string",
			"exclusiveMinimum": 0
		},
		"author": {
			"description": "Name/Handle of the author",
			"type": "string",
			"exclusiveMinimum": 0
		},
		"location": {
			"description": "Coordinates of the event location",
			"type": "object",
			"properties": {
				"latitude": {
					"description": "Latitude of geo coordinates",
					"type": "string",
					"exclusiveMinimum": 0
				},
				"longitude": {
					"description": "Longitude of geo coordinates",
					"type": "string",
					"exclusiveMinimum": 0
				}
			},
			"required": ["latitude", "longitude"]

		},
		"start-date": {
			"description": "The official date and time of the start of the event",
			"type": "string",
			"format": "date-time",
			"exclusiveMinimum": 0
		},
		"end-date": {
			"description": "The official date and time of the end of the event",
			"type": "string",
			"format": "date-time",
			"exclusiveMinimum": 0
		},
		"version": {
			"description": "Version number of the design material",
			"type": "integer",
			"exclusiveMinimum": 0
		},
		"categories": {
			"description": "Map single design assets to categories",
			"type": "object",
			"properties": {
				"logo": {
					"description": "Icon and logo files",
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			}
		}
	},
	"required": ["name", "license", "author", "location", "start-date", "end-date"]
}

=== V1TA5/eli/sample/meta.json
{
	"name": "Night of open Knowledge",
	"license": "CC-BY-NC-SA 4.0",
	"author": "faab_e",
	"location": {"latitude": "53.83420", "longitude": "10.70017"},
	"start-date": "2023-11-03T17:00:00+01:00",
	"end-date": "2023-11-04T20:00:00+01:00",
	"version": 1,
	"categories": {
		"logo": ["nook2023.svg"]
	}
}
